name = "slot-system-01"
account_id = "d487a4f4ab6dd57899955ec5775f10ce"
compatibility_date = "2025-01-06"
main = "workers-site/index.js"

# Workers Sites 설정 (정적 자산 배포)
[site]
bucket = "./dist"

# 환경 변수
[vars]
ENVIRONMENT = "production"

# 빌드 설정
[build]
command = "npm run build"

# 개발 환경 설정
[env.development]
name = "slot-system-01-dev"
vars = { ENVIRONMENT = "development" }

# 스테이징 환경 설정
[env.staging]
name = "slot-system-01-staging"
vars = { ENVIRONMENT = "staging" }

# 프로덕션 환경 설정
[env.production]
name = "slot-system-01"
vars = { ENVIRONMENT = "production" }

# 라우팅 규칙
[[routes]]
pattern = "/*"
zone_name = ""